### ISSUE TITLE
Mirroring not updating

### ISSUE THREAD

**Issue by lewellyn** [gitblit/gitblit#1059]
I've set up a mirror per the instructions at http://gitblit.com/setup_mirrors.html

The source repository is hosted on GitHub Enterprise, and it was mirrored using HTTPS with a username and password. The Gitblit log shows: (sanitized to not give internal user, repo, or hostnames)

```
2016-04-15 00:02:50 [ERROR] Error updating mirror problematic-repository.git
org.eclipse.jgit.api.errors.TransportException: https://gituser@internal.github.enterprise/ORG/problematic-repository.git: Authentication is required but no CredentialsProvider has been registered
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
        at com.gitblit.service.MirrorService.run(MirrorService.java:149)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jgit.errors.TransportException: https://gituser@internal.github.enterprise/ORG/problematic-repository.git: Authentication is required but no CredentialsProvider has been registered
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:492)
        at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:296)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        ... 8 more
```

I notice that the logged URL does not include the password, but it is displayed in the Gitblit Web UI. I've been trying to follow exactly where and how the password may be lost (and hoping it's not a wild goose chase where it's simply not logged…), but I'm not succeeding so far. I'll update this ticket with code, if I manage to solve it on my own.

This is a showstopper bug for me, so I'll be investigating it heavily. However, if you have any suggestions for likely places to look (or know that it's fixed since 1.7.1), I'm all ears. 👂

**Comment by gitblit** [comment]
Hi @lewellyn.  Try changing MirrorService line 149 to something like...

```java
CredentialsProvider creds = null;
URIish fetchUri = new URIish(mirror.getURIs().get(0));
if (fetchUri.getUser() != null && fetchUri.getPass() != null) {
    creds = new UsernamePasswordCredentialsProvider(fetchUri.getUser(), fetchUri.getPass());
}
FetchResult result = git.fetch()
                    .setCredentialsProvider(creds)
                    .setRemote(mirror.getName())
                    .setDryRun(testing).call();
```

If that works, submit a PR and we'll mainstream it.

**Comment by rafi84** [comment]
Thanks it worked with this:

```java
	CredentialsProvider creds = null;
				URIish fetchUri = mirror.getURIs().get(0);
				if (fetchUri.getUser() != null && fetchUri.getPass() != null) {
				    creds = new UsernamePasswordCredentialsProvider(fetchUri.getUser(), fetchUri.getPass());
				}
				FetchResult result = git.fetch()
				                    .setCredentialsProvider(creds)
				                    .setRemote(mirror.getName())
				                    .setDryRun(testing).call();

**Comment by cmichaelis** [comment]
Just ran into this problem on 1.8.0 using Gitblit WAR. Did you ever send in a PR for this, and any chance it can get included in a future update to the WAR distribution? Thanks!

**Comment by paalgyula** [comment]
No not yet. Would you like me to do that?

Best regards:

Gyula, Paál
+36 70 907 5659
paalgyula@paalgyula.com

On 2018. April 20. at 2:07:30, Christopher Michaelis (notifications@github.com) wrote:

Just ran into this problem on 1.8.0 using Gitblit WAR. Did you ever send in a PR for this, and any chance it can get included in a future update to the WAR distribution? Thanks!

**Comment by cmichaelis** [comment]
If you wouldn't mind, that'd be great! Thank you very much!

**Comment by viennem** [comment]
I'm running into the same problem in version 1.8.1 of the jar distribution with the credentials embedded in the origin url or using `git config --global credential.helper store`.
The documentation at http://gitblit.com/setup_mirrors.html says that it is possible to embed the credentials in the origin url.

Has this been fiixed in version 1.9.1?

**Comment by fzs** [comment]
I don't see a pull request for this ever being created. I also did not find one referencing mirroring, either open or closed. So I guess it hasn't been fixed, yet.
