### ISSUE TITLE
error find in gitblit (Java not start)

### ISSUE THREAD

**Issue by sumitguptamca** [gitblit/gitblit#1108]
2016-08-03 01:29:42 [INFO ] ****************************************************                                                                                        *************
2016-08-03 01:29:42 [INFO ]             _____  _  _    _      _  _  _
2016-08-03 01:29:42 [INFO ]            |  __ \(_)| |  | |    | |(_)| |
2016-08-03 01:29:42 [INFO ]            | |  \/ _ | |_ | |__  | | _ | |_
2016-08-03 01:29:42 [INFO ]            | | __ | || __|| '_ \ | || || __|
2016-08-03 01:29:42 [INFO ]            | |_\ \| || |_ | |_) || || || |_
2016-08-03 01:29:42 [INFO ]             \____/|_| \__||_.__/ |_||_| \__|
2016-08-03 01:29:42 [INFO ]                          Gitblit v1.6.2
2016-08-03 01:29:42 [INFO ]
2016-08-03 01:29:42 [INFO ] ****************************************************                                                                                        *************
2016-08-03 01:29:42 [INFO ] Running on Linux (3.10.0-229.20.1.el7.x86_64)
2016-08-03 01:29:42 [INFO ] Logging initialized @779ms
2016-08-03 01:29:43 [INFO ] Using JCE Unlimited Strength Jurisdiction Policy fil                                                                                        es
2016-08-03 01:29:43 [INFO ] Setting up HTTPS transport on port 8443
2016-08-03 01:29:43 [INFO ]    certificate alias = localhost
2016-08-03 01:29:43 [INFO ]    keyStorePath   = /opt/gitblit/data/serverKeyStore                                                                                        .jks
2016-08-03 01:29:43 [INFO ]    trustStorePath = /opt/gitblit/data/serverTrustSto                                                                                        re.jks
2016-08-03 01:29:43 [INFO ]    crlPath        = /opt/gitblit/data/certs/caRevoca                                                                                        tionList.crl
2016-08-03 01:29:43 [INFO ] Setting up HTTP transport on port 8447
2016-08-03 01:29:43 [WARN ] Could not open shutdown monitor on port 8081
java.net.BindException: Address already in use
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:37                                                                                        6)
        at java.net.ServerSocket.bind(ServerSocket.java:376)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at com.gitblit.GitBlitServer$ShutdownMonitorThread.<init>(GitBlitServer.                                                                                        java:518)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:470)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
Exception in thread "Gitblit Shutdown Monitor" java.lang.NullPointerException
        at com.gitblit.GitBlitServer$ShutdownMonitorThread.run(GitBlitServer.jav                                                                                        a:527)
2016-08-03 01:29:43 [INFO ] jetty-9.2.3.v20140905
2016-08-03 01:29:43 [INFO ] NO JSP Support for /, did not find org.apache.jasper                                                                                        .servlet.JspServlet
2016-08-03 01:29:43 [INFO ]
2016-08-03 01:29:43 [INFO ] ----[com.gitblit.manager.IRuntimeManager]----
2016-08-03 01:29:43 [INFO ] Basefolder  : /opt/gitblit/data
2016-08-03 01:29:43 [INFO ] Settings    : /opt/gitblit/data/gitblit.properties
2016-08-03 01:29:43 [INFO ] JVM timezone: Etc/UTC (UTC +0000)
2016-08-03 01:29:43 [INFO ] App timezone: Etc/UTC (UTC +0000)
2016-08-03 01:29:43 [INFO ] JVM locale  : en_US
2016-08-03 01:29:43 [INFO ] App locale  : <client>
2016-08-03 01:29:43 [INFO ] PF4J runtime mode is 'deployment'
2016-08-03 01:29:43 [INFO ] Enabled plugins: []
2016-08-03 01:29:43 [INFO ] Disabled plugins: []
2016-08-03 01:29:43 [INFO ]
2016-08-03 01:29:43 [INFO ] ----[com.gitblit.manager.INotificationManager]----
2016-08-03 01:29:43 [WARN ] Mail service disabled.
2016-08-03 01:29:43 [INFO ]
2016-08-03 01:29:43 [INFO ] ----[com.gitblit.manager.IUserManager]----
2016-08-03 01:29:43 [INFO ] ConfigUserService(/opt/gitblit/data/users.conf)
2016-08-03 01:29:43 [INFO ]
2016-08-03 01:29:43 [INFO ] ----[com.gitblit.manager.IAuthenticationManager]----
2016-08-03 01:29:43 [INFO ] External authentication disabled.
2016-08-03 01:29:44 [INFO ]
2016-08-03 01:29:44 [INFO ] ----[com.gitblit.transport.ssh.IPublicKeyManager]---                                                                                        -
2016-08-03 01:29:44 [INFO ] FileKeyManager (/opt/gitblit/data/ssh)
2016-08-03 01:29:44 [INFO ]
2016-08-03 01:29:44 [INFO ] ----[com.gitblit.manager.IRepositoryManager]----
2016-08-03 01:29:44 [INFO ] Repositories folder : /opt/gitblit/data/git
2016-08-03 01:29:44 [INFO ] Identifying repositories...
2016-08-03 01:29:44 [INFO ] 6 repositories identified with calculated folder siz                                                                                        es in 363 msecs
2016-08-03 01:29:44 [INFO ] Lucene will process indexed branches every 2 minutes                                                                                        .
2016-08-03 01:29:44 [INFO ] Garbage Collector (GC) is disabled.
2016-08-03 01:29:44 [INFO ] Mirror service is disabled.
2016-08-03 01:29:44 [INFO ] Alias UTF-9 & UTF-18 encodings as UTF-8 in JGit
2016-08-03 01:29:44 [INFO ] Preparing 14 day commit cache. please wait...
2016-08-03 01:29:44 [INFO ]   cached 12 commits for app_imatplan.git:refs/heads/                                                                                        master
2016-08-03 01:29:44 [INFO ]   cached 5 commits for dickson_imatplan.git:refs/hea                                                                                        ds/master
2016-08-03 01:29:44 [INFO ] built 14 day commit cache of 17 commits across 2 rep                                                                                        ositories in 161 msecs
2016-08-03 01:29:44 [INFO ]
2016-08-03 01:29:44 [INFO ] ----[com.gitblit.manager.IProjectManager]----
2016-08-03 01:29:44 [INFO ]
2016-08-03 01:29:44 [INFO ] ----[com.gitblit.manager.IFederationManager]----
2016-08-03 01:29:44 [INFO ]
2016-08-03 01:29:44 [INFO ] ----[com.gitblit.manager.IGitblit]----
2016-08-03 01:29:44 [INFO ] Starting services manager...
2016-08-03 01:29:44 [INFO ] Federation passphrase is blank! This server can not                                                                                         be PULLED from.
2016-08-03 01:29:44 [INFO ] Fanout PubSub service is disabled.
2016-08-03 01:29:44 [ERROR] Failed to start Git Daemon on :9418
java.net.BindException: Address already in use
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:37                                                                                        6)
        at java.net.ServerSocket.bind(ServerSocket.java:376)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at com.gitblit.transport.git.GitDaemon.start(GitDaemon.java:209)
        at com.gitblit.manager.ServicesManager.configureGitDaemon(ServicesManage                                                                                        r.java:167)
        at com.gitblit.manager.ServicesManager.start(ServicesManager.java:92)
        at com.gitblit.GitBlit.start(GitBlit.java:103)
        at com.gitblit.GitBlit.start(GitBlit.java:65)
        at com.gitblit.servlet.GitblitContext.startManager(GitblitContext.java:2                                                                                        47)
        at com.gitblit.servlet.GitblitContext.configureContext(GitblitContext.ja                                                                                        va:189)
        at com.gitblit.servlet.GitblitContext.contextInitialized(GitblitContext.                                                                                        java:131)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialize                                                                                        d(ContextHandler.java:798)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialize                                                                                        d(ServletContextHandler.java:444)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextH                                                                                        andler.java:789)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletC                                                                                        ontextHandler.java:294)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java                                                                                        :1341)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.jav                                                                                        a:1334)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandle                                                                                        r.java:741)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:497                                                                                        )
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi                                                                                        feCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container                                                                                        LifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand                                                                                        ler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
2016-08-03 01:29:44 [ERROR] Failed to start SSH daemon on :29418
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:463)
        at sun.nio.ch.Net.bind(Net.java:455)
        at sun.nio.ch.AsynchronousServerSocketChannelImpl.bind(AsynchronousServe                                                                                        rSocketChannelImpl.java:162)
        at org.apache.sshd.common.io.nio2.Nio2Acceptor.bind(Nio2Acceptor.java:58                                                                                        )
        at org.apache.sshd.common.io.nio2.Nio2Acceptor.bind(Nio2Acceptor.java:66                                                                                        )
        at org.apache.sshd.SshServer.start(SshServer.java:343)
        at com.gitblit.transport.ssh.SshDaemon.start(SshDaemon.java:170)
        at com.gitblit.manager.ServicesManager.configureSshDaemon(ServicesManage                                                                                        r.java:183)
        at com.gitblit.manager.ServicesManager.start(ServicesManager.java:93)
        at com.gitblit.GitBlit.start(GitBlit.java:103)
        at com.gitblit.GitBlit.start(GitBlit.java:65)
        at com.gitblit.servlet.GitblitContext.startManager(GitblitContext.java:2                                                                                        47)
        at com.gitblit.servlet.GitblitContext.configureContext(GitblitContext.ja                                                                                        va:189)
        at com.gitblit.servlet.GitblitContext.contextInitialized(GitblitContext.                                                                                        java:131)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialize                                                                                        d(ContextHandler.java:798)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialize                                                                                        d(ServletContextHandler.java:444)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextH                                                                                        andler.java:789)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletC                                                                                        ontextHandler.java:294)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java                                                                                        :1341)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.jav                                                                                        a:1334)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandle                                                                                        r.java:741)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:497                                                                                        )
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi                                                                                        feCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container                                                                                        LifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand                                                                                        ler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
2016-08-03 01:29:44 [WARN ] No ticket service configured.
2016-08-03 01:29:44 [INFO ]
2016-08-03 01:29:44 [INFO ] ----[com.gitblit.manager.IPluginManager]----
2016-08-03 01:29:44 [INFO ] No plugins
2016-08-03 01:29:44 [INFO ]
2016-08-03 01:29:44 [INFO ] All managers started.
2016-08-03 01:29:44 [INFO ]
2016-08-03 01:29:45 [INFO ] [GitBlitWebApp] init: Wicket core library initialize                                                                                        r
2016-08-03 01:29:45 [INFO ] [GitBlitWebApp] init: Wicket extensions initializer
2016-08-03 01:29:45 [INFO ] [GitBlitWebApp] Started Wicket version 1.4.21 in dep                                                                                        loyment mode
2016-08-03 01:29:45 [INFO ] Started o.e.j.w.WebAppContext@43ba1868{/,file:/opt/g                                                                                        itblit/data/temp/webapp/,AVAILABLE}{file:/opt/gitblit/gitblit.jar}
2016-08-03 01:29:45 [WARN ] FAILED ServerConnector@4b044f94{SSL-HTTP/1.1}{0.0.0.                                                                                        0:8443}: java.net.BindException: Address already in use
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:463)
        at sun.nio.ch.Net.bind(Net.java:455)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:                                                                                        223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:32                                                                                        0)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNet                                                                                        workConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java                                                                                        :236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
2016-08-03 01:29:45 [WARN ] FAILED ServerConnector@68ac8a06{HTTP/1.1}{0.0.0.0:84                                                                                        47}: java.net.BindException: Address already in use
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:463)
        at sun.nio.ch.Net.bind(Net.java:455)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:                                                                                        223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:32                                                                                        0)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNet                                                                                        workConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java                                                                                        :236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
2016-08-03 01:29:45 [WARN ] FAILED org.eclipse.jetty.server.Server@707c0d90: Mul                                                                                        tiException[java.net.BindException: Address already in use, java.net.BindExcepti                                                                                        on: Address already in use]
MultiException[java.net.BindException: Address already in use, java.net.BindExce                                                                                        ption: Address already in use]
        at org.eclipse.jetty.server.Server.doStart(Server.java:329)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:463)
        at sun.nio.ch.Net.bind(Net.java:455)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:                                                                                        223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:32                                                                                        0)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNet                                                                                        workConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java                                                                                        :236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:463)
        at sun.nio.ch.Net.bind(Net.java:455)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:                                                                                        223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:32                                                                                        0)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNet                                                                                        workConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java                                                                                        :236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
MultiException[java.net.BindException: Address already in use, java.net.BindExce                                                                                        ption: Address already in use]
        at org.eclipse.jetty.server.Server.doStart(Server.java:329)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:463)
        at sun.nio.ch.Net.bind(Net.java:455)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:                                                                                        223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:32                                                                                        0)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNet                                                                                        workConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java                                                                                        :236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:463)
        at sun.nio.ch.Net.bind(Net.java:455)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:                                                                                        223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:32                                                                                        0)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNet                                                                                        workConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java                                                                                        :236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:463)
        at sun.nio.ch.Net.bind(Net.java:455)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:                                                                                        223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:32                                                                                        0)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNet                                                                                        workConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java                                                                                        :236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:463)
        at sun.nio.ch.Net.bind(Net.java:455)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:                                                                                        223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:32                                                                                        0)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNet                                                                                        workConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java                                                                                        :236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife                                                                                        Cycle.java:68)
        at com.gitblit.GitBlitServer.start(GitBlitServer.java:475)
        at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.moxie.MxLauncher.main(MxLauncher.java:129)

**Comment by sumitguptamca** [comment]
Please send solution this problem

**Comment by gitblit** [comment]
@sumitguptamca Your logs are very complete and the explanation is clear: you are running 2 instances of Gitblit.

The second instance can not start any of the embedded servers (http, https, git, nor ssh) because the first instance has ownership of each of those ports.

**Comment by sumitguptamca** [comment]
how please tell me how to start?

**Comment by sumitguptamca** [comment]
sir please check this line

2016-08-03 01:29:45 [WARN ] FAILED org.eclipse.jetty.server.Server@707c0d9: Mul tiException[java.net.BindException: Address already in use, java.net.BindExcepti on: Address already in use]
MultiException[java.net.BindException: Address already in use, java.net.BindExce ption: Address already in use]

**Comment by gitblit** [comment]
Right.  Port already bound.  It can not be bound by another server ergo "address already in use".  I would check `ps ax`.  I think you'll find another instance launched.

**Comment by sumitguptamca** [comment]
i would check this ps ax . please send me document to fix this problem.

**Comment by gitblit** [comment]
[`ps ax | grep java`](http://linux.die.net/man/1/ps)

**Comment by sumitguptamca** [comment]
sir i will not fix error i am send snap shot pls check and find solution
![gitblit](https://cloud.githubusercontent.com/assets/6875427/17373815/863743c8-59c7-11e6-8755-f9412bd6fdc3.png)

**Comment by gitblit** [comment]
One last thing you could check is the bind interface.  Maybe you are binding `localhost` instead of `0.0.0.0`.  You may also have a firewall blocking access to those ports - that wouldn't surprise me since it looks like you are running CentOS or RHEL.

But you are definitely running multiple instances on that machine with each one trying to bind the same ports on the same interface.

I have no document I can send you, sorry, and there is no further help I can provide you aside from recommending that you use a current version of Gitblit (1.8.0) rather than one that is nearly 2 years old.

Good luck.  Closing issue.
