### ISSUE TITLE
Error receive pack

### ISSUE THREAD

**Issue by jagafirst** [gitblit/gitblit#1203]
I have hosted gitblit GO v1.8.0 server in centos 6.8. But often I got the following errors:
Server Log:
2017-02-23 11:01:35 [ERROR] Internal server error (user TEST) during git git-receive-pack '/GITREPO.git'
com.gitblit.transport.ssh.commands.BaseCommand$Failure: fatal: Cannot receive pack: 
        at com.gitblit.transport.ssh.git.Receive.runImpl(Receive.java:36)
        at com.gitblit.transport.ssh.git.BaseGitCommand.service(BaseGitCommand.java:72)
        at com.gitblit.transport.ssh.git.BaseGitCommand.access$100(BaseGitCommand.java:33)
        at com.gitblit.transport.ssh.git.BaseGitCommand$1.run(BaseGitCommand.java:59)
        at com.gitblit.transport.ssh.commands.BaseCommand$TaskThunk.run(BaseCommand.java:331)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at com.gitblit.utils.WorkQueue$Task.run(WorkQueue.java:332)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jgit.errors.UnpackException: Exception while parsing pack stream
        at org.eclipse.jgit.transport.ReceivePack.service(ReceivePack.java:251)
        at org.eclipse.jgit.transport.ReceivePack.receive(ReceivePack.java:161)
        at com.gitblit.transport.ssh.git.Receive.runImpl(Receive.java:34)

Caused by: java.io.EOFException: Short read of block.
        at org.eclipse.jgit.util.IO.readFully(IO.java:249)
        at org.eclipse.jgit.internal.storage.file.UnpackedObject.open(UnpackedObject.java:105)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openLooseObject(ObjectDirectory.java:441)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:374)
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:142)
        at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:226)
        at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
        at org.eclipse.jgit.transport.BaseReceivePack.checkConnectivity(BaseReceivePack.java:1279)
        at org.eclipse.jgit.transport.BaseReceivePack.receivePackAndCheckConnectivity(BaseReceivePack.java:1007)
        at org.eclipse.jgit.transport.ReceivePack.service(ReceivePack.java:192)
        ... 14 more

CLIENT SIDE ERROR:
remote: Resolving deltas: 100% (303/303)
error: unpack failed: error Short read of block.
fatal: Cannot receive pack: 
To ssh://TEST@IP_ADDRESS:29418/GITREPO.git
 ! [remote rejected] master -> master (n/a (unpacker error))
error: failed to push some refs to 'ssh://TEST@IP_ADDRESS:29418/GITREPO.git'

**Comment by gitblit** [comment]
Are you storing your repos on a local filesystem or on a shared drive (e.g. NFS)?

**Comment by jagafirst** [comment]
I am using local linux file system.

**Comment by flaix** [comment]
When you say NAS, do you have the server running on the NAS or how is that NAS drive connected?

**Comment by victor-anubavam** [comment]
2021-04-12 21:31:36 [ERROR] Internal server error (user admin) during git git-upload-pack '/data.git'
com.gitblit.transport.ssh.commands.BaseCommand$Failure: fatal: Cannot upload pack: 
	at com.gitblit.transport.ssh.git.Upload.runImpl(Upload.java:36)
	at com.gitblit.transport.ssh.git.BaseGitCommand.service(BaseGitCommand.java:72)
	at com.gitblit.transport.ssh.git.BaseGitCommand.access$100(BaseGitCommand.java:33)
	at com.gitblit.transport.ssh.git.BaseGitCommand$1.run(BaseGitCommand.java:59)
	at com.gitblit.transport.ssh.commands.BaseCommand$TaskThunk.run(BaseCommand.java:331)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.gitblit.utils.WorkQueue$Task.run(WorkQueue.java:332)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jgit.transport.UploadPackInternalServerErrorException
	at org.eclipse.jgit.transport.UploadPack.sendPack(UploadPack.java:1397)
	at org.eclipse.jgit.transport.UploadPack.service(UploadPack.java:772)
	at org.eclipse.jgit.transport.UploadPack.upload(UploadPack.java:666)
	at com.gitblit.transport.ssh.git.Upload.runImpl(Upload.java:34)
	... 12 more
Caused by: java.io.IOException: Input/output error
	at java.io.RandomAccessFile.readBytes(Native Method)
	at java.io.RandomAccessFile.read(RandomAccessFile.java:377)
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:436)
	at org.eclipse.jgit.internal.storage.file.PackFile.read(PackFile.java:667)
	at org.eclipse.jgit.internal.storage.file.WindowCache.load(WindowCache.java:289)
	at org.eclipse.jgit.internal.storage.file.WindowCache.getOrLoad(WindowCache.java:368)
	at org.eclipse.jgit.internal.storage.file.WindowCache.get(WindowCache.java:179)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.pin(WindowCursor.java:324)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.copyPackAsIs(WindowCursor.java:244)
	at org.eclipse.jgit.internal.storage.file.PackFile.copyPackAsIs(PackFile.java:355)
	at org.eclipse.jgit.internal.storage.file.LocalCachedPack.copyAsIs(LocalCachedPack.java:85)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.copyPackAsIs(WindowCursor.java:236)
	at org.eclipse.jgit.internal.storage.pack.PackWriter.writePack(PackWriter.java:1013)
	at org.eclipse.jgit.transport.UploadPack.sendPack(UploadPack.java:1538)
	at org.eclipse.jgit.transport.UploadPack.sendPack(UploadPack.java:1391)
	... 15 more
