### ISSUE TITLE
Unable to view summary/tickets page

### ISSUE THREAD

**Issue by drognisep** [gitblit/gitblit#1237]
[Originally posted on super**user**](https://superuser.com/questions/1210991/gitblit-war-wicketruntimeexception-on-any-repository-summary-page)

I'm currently unable to view the summary page on any repository, or view tickets. Please see the super**user** link above for detailed information.

Here's the stack trace for attempting to load a summary page, specifically for **jPortfolio**:
```
2017-05-19 18:36:34 [ERROR] Can't instantiate page using constructor public com.gitblit.wicket.pages.SummaryPage(org.apache.wicket.PageParameters) and argument r = "jPortfolio.git"
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor public com.gitblit.wicket.pages.SummaryPage(org.apache.wicket.PageParameters) and argument r = "jPortfolio.git"
        at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:212)
        at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:89)
        at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.newPage(BookmarkablePageRequestTarget.java:305)
        at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.getPage(BookmarkablePageRequestTarget.java:320)
        at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.processEvents(BookmarkablePageRequestTarget.java:234)
        at org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)
        at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1279)
        at org.apache.wicket.RequestCycle.step(RequestCycle.java:1358)
        at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1465)
        at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
        at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.gitblit.servlet.EnforceAuthenticationFilter.doFilter(EnforceAuthenticationFilter.java:99)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.gitblit.servlet.ProxyFilter$1.doFilter(ProxyFilter.java:89)
        at com.gitblit.servlet.ProxyFilter.doFilter(ProxyFilter.java:92)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor133.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:188)
        ... 41 more
Caused by: java.lang.NullPointerException
        at com.gitblit.manager.ServicesManager.getRepositoryUrls(ServicesManager.java:279)
        at com.gitblit.wicket.panels.RepositoryUrlPanel.onInitialize(RepositoryUrlPanel.java:83)
        at org.apache.wicket.Component.fireInitialize(Component.java:4105)
        at org.apache.wicket.MarkupContainer.initialize(MarkupContainer.java:433)
        at org.apache.wicket.MarkupContainer.addedComponent(MarkupContainer.java:1000)
        at org.apache.wicket.MarkupContainer.add(MarkupContainer.java:142)
        at com.gitblit.wicket.pages.SummaryPage.<init>(SummaryPage.java:130)
        ... 45 more
```

**Comment by pingunaut** [comment]
I just took a look at the code. The error occurs while trying to get the users preferred URL protocol.
The error can be reproduced by adding an unsupported url in gitblit.properties like this:
![image](https://cloud.githubusercontent.com/assets/1359917/26287167/b740b1d2-3e75-11e7-97a0-10a57918cde1.png)

The error can be fixed locally by adding a null check to url.transport in ServicesManager.java:279
![image](https://cloud.githubusercontent.com/assets/1359917/26287227/4674b942-3e77-11e7-9a05-6ded0fdb61c1.png)

However it just fixes the "internal error" and shows the URL in the panel. The root cause is the unsupported protocol which is somewhere else.

**Comment by drognisep** [comment]
I have nothing in that property in default.properties, and that property doesn't exists in gitblit.properties. Should I fill it with something like what is shown in the comments above the property, or are those values set already by default?

```
# e.g.
# web.otherUrls = ssh://localhost/git/{0} git://localhost/git/{0} https://{1}@localhost/r/{0}
```

**Comment by drognisep** [comment]
@pingunaut Tried overriding that property in gitblit.properties, but the same exception happened.

I *did* notice that this info message is popping up immediately before the stack trace in catalina.out:
```
2017-05-21 19:22:00 [INFO ] Unknown transport, push rejected!
```
The URL for the link to the summary page on the repositories page is of the form https://example.com/git/summary/?r=jPortfolio.git

So I don't think that it should be getting "unknown transport" like the log message above says.

**Comment by drognisep** [comment]
@pingunaut **I had a break-through!** Based on the "Unknown transport" message I changed my preferred transport in profile settings from HTTPS to SSH, and I'm now able to view the repository and ticket pages, but I'm still seeing the info message above in the log, so I'm wondering just how relevant it is to this particular issue.

Any ideas on this?

**Comment by pingunaut** [comment]
@drognisep this is good news. When you are on the summary page of a repository, what urls do you see in the dropdown panel? (the one that looks like this):
![image](https://cloud.githubusercontent.com/assets/1359917/26307399/9060fd36-3ef4-11e7-8400-47136642415a.png)

**Comment by drognisep** [comment]
I have mostly the same, except that https link is quoted for some reason.

![image](https://cloud.githubusercontent.com/assets/8890988/26313820/a9490afa-3ed1-11e7-9742-4482642f128d.png)

**Comment by pingunaut** [comment]
Alright here we go:
"https
is not a valid protocol :-)
the only remaining questions is: how did the quotes get there.. i'll try to have a look later

**Comment by drognisep** [comment]
I don't think I've added quotes in configuration anywhere (not sure why I would). Makes sense why it's complaining. Do you think it's configuration or logic?

**Comment by pingunaut** [comment]
Hmm, didn't find anything in the logic that would explain it. Maybe it's your domain configuration (in gitblit.properties or defaults.properties)?
I was able to exactly reproduce the behavior by setting:
web.canonicalUrl = "https://saylorsolutions.com/git/"

**Comment by drognisep** [comment]
@pingunaut As it turns out, that's exactly what I did. Don't know why, but that's it. Thanks for your help!
