### ISSUE TITLE
Can't instantiate page using constructor public com.gitblit.wicket.pages.MyTicketsPage()

### ISSUE THREAD

**Issue by bviktor** [gitblit/gitblit#1251]
A specific user gets "Internal error" page when trying to visit his "tickets" page. Here's the log excerpt:

~~~
2017-07-28 19:21:48 [ERROR] Can't instantiate page using constructor public com.gitblit.wicket.pages.MyTicketsPage()
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor public com.gitblit.wicket.pages.MyTicketsPage()
        at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:212)
        at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:57)
        at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.newPage(BookmarkablePageRequestTarget.java:298)
        at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.getPage(BookmarkablePageRequestTarget.java:320)
        at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.processEvents(BookmarkablePageRequestTarget.java:234)
        at org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)
        at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1279)
        at org.apache.wicket.RequestCycle.step(RequestCycle.java:1358)
        at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1465)
        at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
        at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.gitblit.servlet.EnforceAuthenticationFilter.doFilter(EnforceAuthenticationFilter.java:99)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.gitblit.servlet.ProxyFilter$1.doFilter(ProxyFilter.java:89)
        at com.gitblit.servlet.ProxyFilter.doFilter(ProxyFilter.java:92)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:192)
        ... 40 more
Caused by: java.lang.NullPointerException
        at com.gitblit.wicket.pages.MyTicketsPage.correspondingRepositories(MyTicketsPage.java:494)
        at com.gitblit.wicket.pages.MyTicketsPage.<init>(MyTicketsPage.java:282)
        at com.gitblit.wicket.pages.MyTicketsPage.<init>(MyTicketsPage.java:60)
        ... 45 more
~~~

Any ideas how to debug this?

**Comment by gitblit** [comment]
> Caused by: java.lang.NullPointerException
>        at com.gitblit.wicket.pages.MyTicketsPage.correspondingRepositories(MyTicketsPage.java:494)

That's the [culprit](https://github.com/gitblit/gitblit/blob/master/src/main/java/com/gitblit/wicket/pages/MyTicketsPage.java#L494).

Assuming you are running the latest version, it looks like a repository is no longer available probably due to manual deletion or manual relocation.  You could try [rebuilding the Lucene index](http://gitblit.com/tickets_replication.html#H13).

**Comment by bviktor** [comment]
Thanks a whole lot, James, performed a reindex and waiting on confirmation from our dev.

What do you think of triggering this from within code? Is there a sane way to detect if a limited reindex needs to be done? E.g.

~~~
if (action == move || action == delete)
{
  if (repo.hasTickets())
  {
    reindex(repo)
  }
}
~~~

**Comment by gitblit** [comment]
Should already be covered.  On [move](https://github.com/gitblit/gitblit/blob/master/src/main/java/com/gitblit/manager/GitblitManager.java#L1026-L1043) and on [delete](https://github.com/gitblit/gitblit/blob/master/src/main/java/com/gitblit/manager/GitblitManager.java#L1055-L1065).

**Comment by bviktor** [comment]
Oh, I realized just now. I had to archive a few repos and move them out from the VM because disk was filling up.

Ok, nevermind then, it was most certainly because of that :) Many thanks for your swift responses!
