### ISSUE TITLE
Can I use network folder (shared folder) as repositoriesFolder

### ISSUE THREAD

**Issue by KennethWon** [gitblit/gitblit#1261]
Hello all,

I set up the gitblit in Windows environment, and I want yo use a network folder (shared folder) as repositoriesFolder, so I set the [ git.repositoriesFolder = Z:/gitrepository ] , which Z drive is a network drive, it mapped to \\10.18.19.38\Test.
When I create a new repository, it threw the following error.

My question is can I usenetwork folder (shared folder) as repositoriesFolder? If it can, how can I make it possible.

Thanks and Best Regards,
Kenneth

The Error:

2017-09-21 14:32:45 [INFO ] create repository Test.git
2017-09-21 14:32:45 [ERROR] Method onFormSubmitted of interface org.apache.wicket.markup.html.form.IFormSubmitListener targeted at component [MarkupContainer [Component id = editForm]] threw an exception
org.apache.wicket.WicketRuntimeException: Method onFormSubmitted of interface org.apache.wicket.markup.html.form.IFormSubmitListener targeted at component [MarkupContainer [Component id = editForm]] threw an exception
	at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:193)
	at org.apache.wicket.request.target.component.listener.ListenerInterfaceRequestTarget.processEvents(ListenerInterfaceRequestTarget.java:73)
	at org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)
	at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1279)
	at org.apache.wicket.RequestCycle.step(RequestCycle.java:1358)
	at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1465)
	at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
	at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
	at com.gitblit.servlet.EnforceAuthenticationFilter.doFilter(EnforceAuthenticationFilter.java:99)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
	at com.gitblit.servlet.ProxyFilter$1.doFilter(ProxyFilter.java:89)
	at com.gitblit.servlet.ProxyFilter.doFilter(ProxyFilter.java:92)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:182)
	... 37 more
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Creating directories for Z:\gitrepository\Test.git failed
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:118)
	at com.gitblit.utils.JGitUtils.createRepository(JGitUtils.java:302)
	at com.gitblit.manager.RepositoryManager.updateRepositoryModel(RepositoryManager.java:1399)
	at com.gitblit.manager.GitblitManager.updateRepositoryModel(GitblitManager.java:1038)
	at com.gitblit.wicket.pages.NewRepositoryPage$1.onSubmit(NewRepositoryPage.java:139)
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1595)
	at org.apache.wicket.markup.html.form.Form.process(Form.java:960)
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:922)
	... 42 more
Caused by: java.io.IOException: Creating directories for Z:\gitrepository\Test.git failed
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:370)
	at org.eclipse.jgit.internal.storage.file.FileRepository.create(FileRepository.java:271)
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:115)
	... 49 more
2017-09-21 14:32:47 [INFO ] 0 repositories identified with calculated folder sizes in 0 msecs

**Comment by gitblit** [comment]
Gitblit & JGit do not like shared network directories.  This has to do with keeping open file handles to the pack files.  I advise you to switch to local storage.

**Comment by fzs** [comment]
Closing as answered, no further feedback received.
