### ISSUE TITLE
gitblit can not run on Java-9

### ISSUE THREAD

**Issue by godsay1983** [gitblit/gitblit#1262]
D:\gitblit-1.8.0>gitblit
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.moxie.MxLauncher.addJarFile(MxLauncher.java:170)
        at org.moxie.MxLauncher.main(MxLauncher.java:117)
Exception in thread "main" java.lang.NoClassDefFoundError: org/kohsuke/args4j/CmdLineException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at org.moxie.MxLauncher.main(MxLauncher.java:127)
Caused by: java.lang.ClassNotFoundException: org.kohsuke.args4j.CmdLineException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more

**Comment by gitblit** [comment]
Awesome!​  Java 9 is progress!

-J

**Comment by ve3** [comment]
I'm installed Java 8 (JRE) but Gitblit still can't run.
Netbeans use this Java and working but Gitblit is not.
I'm not sure that do I miss something or require any additional setup before Gitblit setup.

**Comment by chirontt** [comment]
To use gitblit with Java 9 and later version, the gitblit.cmd file should be modified as followed:

`@java -cp gitblit.jar;"%CD%\ext\*" com.gitblit.GitBlitServer --baseFolder data %*`

i.e. don't use the -jar option when starting up the gitblit server.
