### ISSUE TITLE
rror: A JNI error has occurred, please check your installation and try again             

### ISSUE THREAD

**Issue by lbdyck** [gitblit/gitblit#1368]
When I  start gitblit I'm getting this error - any advice:

**Using java version:**

java version "1.8.0_241"                                                                                                  
Java(TM) SE Runtime Environment (build 8.0.6.7 - pmz6480sr6fp7-20200312_01(SR6 FP7))                                      
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390x-64-Bit Compressed References 20200219_440062 (JIT enabled, AOT enabled)        
OpenJ9   - 3088245                                                                                                        
OMR      - eb95a4d                                                                                                        
IBM      - 83517b6)                                                                                                       
JCL - 20200310_01 based on Oracle jdk8u241-b07                                                                            

**Contents of gitblit.sh**

#!/bin/bash                                                                     
java -Dfile.encoding=UTF-8 -jar gitblit.jar  baseFolder data                    

**Probelm**

/u/splbd/work/gitblit-1.9.1>sh gitblit.sh                                                          
Error: A JNI error has occurred, please check your installation and try again                      
Exception in thread "main" java.lang.NoClassDefFoundError: org.kohsuke.args4j.CmdLineException     
        at java.lang.J9VMInternals.prepareClassImpl(Native Method)                                 
        at java.lang.J9VMInternals.prepare(J9VMInternals.java:304)                                 
        at java.lang.Class.getMethodHelper(Class.java:1247)                                        
        at java.lang.Class.getMethod(Class.java:1191)                                              
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:556)                  
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:538)                   
Caused by: java.lang.ClassNotFoundException: org.kohsuke.args4j.CmdLineException                   
        at java.net.URLClassLoader.findClass(URLClassLoader.java:610)                              
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:944)                             
        at java.lang.ClassLoader.loadClass(ClassLoader.java:889)                                   
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)                           
        at java.lang.ClassLoader.loadClass(ClassLoader.java:872)                                   
        ... 6 more

**Comment by flaix** [comment]
You are running this on z/OS. I guess you may have followed Henri Kuiper's HowTo?
Maybe you are using a different JVM than he did?

**Comment by lbdyck** [comment]
I followed Henri's instructions.  I've tried Java 7, 7.1, and 8.0 - both 31 and 64-bit versions.  I have sent Henri an e-mail :)

**Comment by TomaszSzt** [comment]
@lbdyck lbdyck

The java.lang.ClassNotFoundException: org.kohsuke.args4j.CmdLineException happens if You start it like You did. It seems, that jar file is missing to point at least that dependency. I can duplicate it on Windows with exactly that kind of obvious command.

The command from gitblit.sh / gitblit.cmd scripts works fine
java -cp "gitblit.jar:ext/*" com.gitblit.GitBlitServer --baseFolder data

**Comment by HuangZhuo** [comment]
Make sure `gitblit-1.9.1\ext\args4j-2.0.29.jar` is exist
