### ISSUE TITLE
Unable to browse log for any repository

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#320]
Originally reported on Google Code with ID 24
```
INFO  Found more URL path parts then expected, these will be ignored. Url: 'http://192.168.41.84:8445/gitblit/log/gitblit-crowd.git/refs/heads/master',
mountpath: 'log', urlPath: 'gitblit-crowd.git/refs/heads/master', expected 2 parameters
was 4
INFO  Loading properties files from jar:file:/home/pf/gitblit/gitblit.jar!/com/gitblit/wicket/GitBlitWebApp.properties
INFO  Loading properties files from jar:file:/home/pf/gitblit/ext/wicket-1.4.18.jar!/org/apache/wicket/Application.properties
ERROR /home/pf/gitblit/git/gitblit-crowd.git failed to get refs revlog for path null
java.lang.NullPointerException
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:809)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:724)
	at com.gitblit.utils.JGitUtils.getRevLog(JGitUtils.java:893)
	at com.gitblit.utils.JGitUtils.getRevLog(JGitUtils.java:854)
	at com.gitblit.wicket.panels.LogPanel.<init>(LogPanel.java:65)
	at com.gitblit.wicket.pages.LogPage.<init>(LogPage.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:188)
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:89)
	at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.newPage(BookmarkablePageRequestTarget.java:305)
	at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.getPage(BookmarkablePageRequestTarget.java:320)
	at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.processEvents(BookmarkablePageRequestTarget.java:234)
	at org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)
	at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1252)
	at org.apache.wicket.RequestCycle.step(RequestCycle.java:1331)
	at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1438)
	at org.apache.wicket.RequestCycle.request(RequestCycle.java:546)
	at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:476)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:937)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:871)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
	at org.eclipse.jetty.server.Server.handle(Server.java:346)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:589)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1048)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:601)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:535)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
	at java.lang.Thread.run(Thread.java:662)

```

Reported by `trygvis` on 2011-10-10 06:29:27

**Comment by steveno** [comment]
Should this issue be closed?

**Comment by gitblit** [comment]
Hmm.  Looks like the GoogleCode import didn't close all issues correctly. Doh!

**Comment by steveno** [comment]
:+1: 

In that case you should close #314 and #310 too.

**Comment by gitblit** [comment]
Thanks.  Done.
