### ISSUE TITLE
gitblit doesn't show any commit or any diff after some push

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#598]
Originally reported on Google Code with ID 302

```
What steps will reproduce the problem?
1. bare repository is viewable by gitblit
2. after some push on this bare repository gitblit doesn't show any commit or any diff
3. error in log file (see attached file) : ERROR failed to generate commit diff!
org.eclipse.jgit.errors.MissingObjectException: Missing blob ef2cedf94e1dcc6a1c95c0dfdcea97015565677c
    at org.eclipse.jgit.storage.file.WindowCursor.open(WindowCursor.java:127)
    at org.eclipse.jgit.diff.ContentSource$ObjectReaderSource.open(ContentSource.java:146)
    at org.eclipse.jgit.diff.ContentSource$Pair.open(ContentSource.java:330)
    at org.eclipse.jgit.diff.DiffFormatter.open(DiffFormatter.java:989)
    at org.eclipse.jgit.diff.DiffFormatter.createFormatResult(DiffFormatter.java:915)
4. restart gitblit and no problem until another push (see attached file)


What is the expected output? What do you see instead?
- can you explain us why gitblit can't read correctly this repository after some push
? but it's ok after restart without change anything on the repository
- can you tell me how to have time in each line of log file to help me to understand
problems ?

What version of the product are you using? On what operating system?
- v1.2.1 on windows
- not connected on internet

Please provide any additional information below.


```

Reported by `bruno.usbvolley` on 2013-08-29 13:11:41

<hr>
- _Attachment: [gitblit-stdout.2013-08-27.log](https://storage.googleapis.com/google-code-attachments/gitblit/issue-302/comment-0/gitblit-stdout.2013-08-27.log)_

**Comment by moley** [comment]
Hi, perhaps it doesn't have to to with both windows or samba. 
I am on wa mac and facing this problem using jgit directly. Perhaps it is an jgit - issue?
