### ISSUE TITLE
Error with login form

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#608]
Originally reported on Google Code with ID 312
```
What steps will reproduce the problem?
1. Enter to a repository page as anonymous user
2. Click at login form without enter any information in the inputs

What is the expected output? What do you see instead?
An alert about fill login/password info, but a error page is displayed

What version of the product are you using? On what operating system?
Gitblit 1.3.2 at CentOS 6

Please provide any additional information below.
ERROR A child with id 'projectTitle' already exists:
[Page class = com.gitblit.wicket.pages.LogPage, id = 0, version = 1, ajax = 0]
java.lang.IllegalArgumentException: A child with id 'projectTitle' already exists:
[Page class = com.gitblit.wicket.pages.LogPage, id = 0, version = 1, ajax = 0]
        at org.apache.wicket.MarkupContainer.add(MarkupContainer.java:145)
        at com.gitblit.wicket.pages.RepositoryPage.setupPage(RepositoryPage.java:248)
        at com.gitblit.wicket.pages.RepositoryPage.onBeforeRender(RepositoryPage.java:574)
        at org.apache.wicket.Component.internalBeforeRender(Component.java:1069)
        at org.apache.wicket.Component.beforeRender(Component.java:1103)
        at org.apache.wicket.Component.prepareForRender(Component.java:2297)
        at org.apache.wicket.Page.prepareForRender(Page.java:1545)
        at org.apache.wicket.Component.prepareForRender(Component.java:2329)
        at org.apache.wicket.Page.renderPage(Page.java:912)
        at org.apache.wicket.protocol.http.WebRequestCycle.redirectTo(WebRequestCycle.java:201)
        at org.apache.wicket.request.target.component.PageRequestTarget.respond(PageRequestTarget.java:58)
        at org.apache.wicket.request.AbstractRequestCycleProcessor.respond(AbstractRequestCycleProcessor.java:105)
        at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1287)
        at org.apache.wicket.RequestCycle.step(RequestCycle.java:1358)
        at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1465)
        at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
        at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1300)
        at com.gitblit.EnforceAuthenticationFilter.doFilter(EnforceAuthenticationFilter.java:87)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1300)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:556)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:363)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Unknown Source)


```

Reported by `doropeza` on 2013-09-19 17:36:15

**Comment by paulsputer** [comment]
issue duplicated in #1031 attempted fix in #1032 which led to regression #1034 final fix merged in PR #1035
