### ISSUE TITLE
error creating repository on arm/cubieboard

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#820]
Originally reported on Google Code with ID 524

```
Creating a new repository on gitblit 1.6.2 brings an internal error and the following
log-messages:


org.apache.wicket.WicketRuntimeException: Method onFormSubmitted of interface org.apache.wicket.markup.html.form.IFormSubmitListener
targeted at component [MarkupContainer [Component id = editForm]] threw an exception
        at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:193)
        at org.apache.wicket.request.target.component.listener.ListenerInterfaceRequestTarget.processEvents(ListenerInterfaceRequestTarget.java:73)
        at org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)
        at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1279)
        at org.apache.wicket.RequestCycle.step(RequestCycle.java:1358)
        at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1465)
        at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
        at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at com.gitblit.servlet.EnforceAuthenticationFilter.doFilter(EnforceAuthenticationFilter.java:87)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at com.gitblit.servlet.ProxyFilter$1.doFilter(ProxyFilter.java:74)
        at com.gitblit.servlet.ProxyFilter.doFilter(ProxyFilter.java:77)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:182)
        ... 31 more
Caused by: java.lang.UnsatisfiedLinkError: JNA native support (/com/sun/jna/linux-arm/libjnidispatch.so)
not found in resource path
        at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:734)
        at com.sun.jna.Native.loadNativeLibrary(Native.java:708)
        at com.sun.jna.Native.<clinit>(Native.java:127)
        at com.gitblit.utils.JnaUtils.getUnixCLibrary(JnaUtils.java:358)
        at com.gitblit.utils.JnaUtils.setFilemode(JnaUtils.java:144)
        at com.gitblit.utils.JnaUtils.setFilemode(JnaUtils.java:122)
        at com.gitblit.utils.JGitUtils.adjustSharedPerm(JGitUtils.java:442)
        at com.gitblit.utils.JGitUtils.createRepository(JGitUtils.java:298)
        at com.gitblit.manager.RepositoryManager.updateRepositoryModel(RepositoryManager.java:1387)
        at com.gitblit.manager.GitblitManager.updateRepositoryModel(GitblitManager.java:1059)
        at com.gitblit.GitBlit.updateRepositoryModel(GitBlit.java:301)
        at com.gitblit.wicket.pages.NewRepositoryPage$1.onSubmit(NewRepositoryPage.java:139)
        at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1595)
        at org.apache.wicket.markup.html.form.Form.process(Form.java:960)
        at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:922)
        ... 35 more

```

Reported by `marcus.hunger` on 2014-11-03 21:56:36

**Comment by fzs** [comment]
Actually, there _is_ a native ARM lib.
@fnordian, is this still an issue for you or have you solved it by not using shared repos?
If it is still an issue, check the `ext` subfolder of Gitblit for the `jna.jar`, see which version it is and if it includes an ARM native library.

**Comment by fnordian** [comment]
It's not an issue for me anymore.

**Comment by fzs** [comment]
@fnordian, did you get this fixed, so maybe for others with the same problem there is a solution,
or is it not a use case for you anymore?

**Comment by fnordian** [comment]
@fzs I stopped using gitblit. Sorry, I am not able to test this anymore.
