### ISSUE TITLE
`org.slf4j:slf4j-api` is missing from Gitblit Manager in developer branch

### ISSUE THREAD

**Issue by yyjdelete** [gitblit/gitblit#909]
`org.slf4j:slf4j-api` is missing from Gitblit Manager, tested with d87b81
```
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at org.eclipse.jgit.util.FS.<clinit>(FS.java:114)
        at com.gitblit.client.GitblitManager.getConfig(GitblitManager.java:400)
        at com.gitblit.client.GitblitManager.setSizeAndPosition(GitblitManager.java:122)
        at com.gitblit.client.GitblitManager.initialize(GitblitManager.java:113)

        at com.gitblit.client.GitblitManager.access$700(GitblitManager.java:77)
        at com.gitblit.client.GitblitManager$7.run(GitblitManager.java:457)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 20 more
```

**Comment by yyjdelete** [comment]
build with `ant buildManager`, unpack `manager-1.7.0-SNAPSHOT.zip` and run it
then got this expection

**Comment by gitblit** [comment]
Thanks for the report.  Fixed on develop.
