### ISSUE TITLE
trouble moving BranchTicketService tickets to 1.7

### ISSUE THREAD

**Issue by aperomsik** [gitblit/gitblit#918]
Thanks for gitblit -- it's a great tool.

I built 1.7-SNAPSHOT using eclipse, and updated my installation. It is mostly running fine but it can't find my tickets. I'm using BranchTicketService.

When clicking on "my tickets" I was getting an error like this:

    2015-09-17 13:42:26 [ERROR] Exception while searching for (createdby:peromsik OR responsible:peromsik OR watchedby:peromsik OR mentions:peromsik)
    java.lang.IllegalArgumentException: Could not load codec 'Lucene46'.  Did you forget to add lucene-backward-codecs.jar?

So I added a line for lucene-backward-codecs to build.moxie and tried again, but it still doesn't work. New exception:

    2015-09-17 13:55:39 [ERROR] Exception while searching for (createdby:peromsik OR responsible:peromsik OR watchedby:peromsik OR mentions:peromsik)
    java.lang.IllegalStateException: unexpected docvalues type NONE for field 'created' (expected=NUMERIC). Use UninvertingReader or index with docvalues.
        at org.apache.lucene.index.DocValues.checkField(DocValues.java:208)
        at org.apache.lucene.index.DocValues.getNumeric(DocValues.java:227)
        at org.apache.lucene.search.FieldComparator$NumericComparator.getNumericDocValues(FieldComparator.java:167)
        at org.apache.lucene.search.FieldComparator$NumericComparator.doSetNextReader(FieldComparator.java:153)
        at org.apache.lucene.search.SimpleFieldComparator.getLeafComparator(SimpleFieldComparator.java:36)
        at org.apache.lucene.search.FieldValueHitQueue.getComparators(FieldValueHitQueue.java:183)
        at org.apache.lucene.search.TopFieldCollector$NonScoringCollector.getLeafCollector(TopFieldCollector.java:141)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:762)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:485)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:694)
        at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:679)
        at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:621)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:527)
        at com.gitblit.tickets.TicketIndexer.queryFor(TicketIndexer.java:412)
        at com.gitblit.tickets.ITicketService.queryFor(ITicketService.java:1257)
        at com.gitblit.wicket.pages.MyTicketsPage.query(MyTicketsPage.java:475)
        at com.gitblit.wicket.pages.MyTicketsPage.<init>(MyTicketsPage.java:281)
        at com.gitblit.wicket.pages.MyTicketsPage.<init>(MyTicketsPage.java:61)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:192)
        at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:57)
        at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.newPage(BookmarkablePageRequestTarget.java:298)
        at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.getPage(BookmarkablePageRequestTarget.java:320)
        at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.processEvents(BookmarkablePageRequestTarget.java:234)
        at org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)
        at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1279)
        at org.apache.wicket.RequestCycle.step(RequestCycle.java:1358)
        at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1465)
        at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
        at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.gitblit.servlet.EnforceAuthenticationFilter.doFilter(EnforceAuthenticationFilter.java:99)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.gitblit.servlet.ProxyFilter$1.doFilter(ProxyFilter.java:89)
        at com.gitblit.servlet.ProxyFilter.doFilter(ProxyFilter.java:82)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:744)

**Comment by aperomsik** [comment]
Just to confirm: As a temporary workaround, rolling back to commit 61bb29d (undoing Lucene upgrade) brings my tickets back.

**Comment by gitblit** [comment]
Thanks for the report.  I saw this too.  I reverted #915, the update to Lucene 5, because it solves no problem that Gitblit has.
