### ISSUE TITLE
GitBlit/Java Melody logs out usernames and passwords 

### ISSUE THREAD

**Issue by Benjamin321** [gitblit/gitblit#926]
While tracking reasons for heavy load and CPU usage on the machine that GitBlit runs on , I stumbled over log entries in the Details of "Statistics for System Errlogs - 1 month" (translated freely from german: "Statistiken für System Fehlerlogs - 1 Monat" ) view of Java Melody:
```
ERROR [org.apache.wicket.RequestCycle] Can't instantiate page using constructor public com.gitblit.wicket.pages.MyDashboardPage(org.apache.wicket.PageParameters) and argument username = "[user]" id2_hf_0 = "[]" password = "[mypassword]"
```
With user and password being the real usernames and password of our LDAP users. 
Now I am trying to find the source of that message. I couldn't find it in the configured GitBlit logs. Where can I find that log?

And please consider this a major bug.

**Comment by gitblit** [comment]
That exception is thrown by Wicket, not by Gitblit itself which is why you
can't find it.  It appears users are trying to login while on the dashboard
page and it's throwing an exception for some reason.  The username and
password values are from the embedded login form at the top of the page.

**Comment by Benjamin321** [comment]
Thanks for the fast reply. Do you have any clue where Wicket logs to? I am currently unsure wether I have to ask my whole userbase to reset their productive LDAP passwords or just a few people.

**Comment by gitblit** [comment]
If you are running GO, Wicket logs to a txt file in the logs directory. If
you are running WAR it logs to the container's logger.  Resetting passwords
will not solve the underlying error which causes them to be logged.  Is
there more to the stacktrace?

**Comment by Benjamin321** [comment]
Ah, I greped through the log folder and found the Stacktrace in the ``gitblit-stdout``. And I am running GO.

```
2015-09-22 13:35:20 [ERROR] Can't instantiate page using constructor public com.gitblit.wicket.pages.MyDashboardPage(org.apache.wicket.PageParameters) and argument username = "[myuser]" id2_hf_0 = "[]" password = "[mypassword]"
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor public com.gitblit.wicket.pages.MyDashboardPage(org.apache.wicket.PageParameters) and argument username = "[myuser]" id2_hf_0 = "[]" password = "[mypassword]"
	at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:212)
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:89)
	at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.newPage(BookmarkablePageRequestTarget.java:305)
	at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.getPage(BookmarkablePageRequestTarget.java:320)
	at org.apache.wicket.request.target.component.BookmarkableListenerInterfaceRequestTarget.processEvents(BookmarkableListenerInterfaceRequestTarget.java:126)
	at org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)
	at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1279)
	at org.apache.wicket.RequestCycle.step(RequestCycle.java:1358)
	at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1465)
	at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
	at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at com.gitblit.servlet.EnforceAuthenticationFilter.doFilter(EnforceAuthenticationFilter.java:87)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at com.gitblit.servlet.ProxyFilter$1.doFilter(ProxyFilter.java:74)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:202)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:180)
	at com.gitblit.plugin.javamelody.GitblitMonitoringFilter.doFilter(GitblitMonitoringFilter.java:74)
	at com.gitblit.servlet.ProxyFilter$1.doFilter(ProxyFilter.java:72)
	at com.gitblit.servlet.ProxyFilter.doFilter(ProxyFilter.java:77)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:188)
	... 38 more
Caused by: java.lang.NullPointerException
	at com.gitblit.wicket.pages.RootPage$UserMenu.onInitialize(RootPage.java:611)
	at org.apache.wicket.Component.fireInitialize(Component.java:4105)
	at org.apache.wicket.MarkupContainer.initialize(MarkupContainer.java:433)
	at org.apache.wicket.MarkupContainer.addedComponent(MarkupContainer.java:1000)
	at org.apache.wicket.MarkupContainer.add(MarkupContainer.java:142)
	at com.gitblit.wicket.pages.RootPage.setupPage(RootPage.java:174)
	at com.gitblit.wicket.pages.MyDashboardPage.setup(MyDashboardPage.java:71)
	at com.gitblit.wicket.pages.MyDashboardPage.<init>(MyDashboardPage.java:62)
	... 43 more
```

I was just confused in the beginnging, since there are similar StackTraces that I thought was directly related and just missing the parameters in the message.

``` 
2015-09-28 15:51:13 [ERROR] Can't instantiate page using constructor public com.gitblit.wicket.pages.MyDashboardPage()
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor public com.gitblit.wicket.pages.MyDashboardPage()
	at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:212)
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:57)
	at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.newPage(BookmarkablePageRequestTarget.java:298)
	at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.getPage(BookmarkablePageRequestTarget.java:320)
	at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.respond(BookmarkablePageRequestTarget.java:261)
	at org.apache.wicket.request.AbstractRequestCycleProcessor.respond(AbstractRequestCycleProcessor.java:105)
	at org.apache.wicket.RequestCycle.respond(RequestCycle.java:1296)
	at org.apache.wicket.RequestCycle.step(RequestCycle.java:1363)
	at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1465)
	at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
	at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at com.gitblit.servlet.EnforceAuthenticationFilter.doFilter(EnforceAuthenticationFilter.java:87)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at com.gitblit.servlet.ProxyFilter$1.doFilter(ProxyFilter.java:74)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:202)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:180)
	at com.gitblit.plugin.javamelody.GitblitMonitoringFilter.doFilter(GitblitMonitoringFilter.java:74)
	at com.gitblit.servlet.ProxyFilter$1.doFilter(ProxyFilter.java:72)
	at com.gitblit.servlet.ProxyFilter.doFilter(ProxyFilter.java:77)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:192)
	... 38 more
Caused by: java.util.MissingResourceException: Unable to find property: 'gb.failedToRead' for component:  [class=com.gitblit.wicket.pages.MyDashboardPage]
	at org.apache.wicket.Localizer.getString(Localizer.java:344)
	at org.apache.wicket.Localizer.getString(Localizer.java:119)
	at org.apache.wicket.Component.getString(Component.java:1968)
	at org.apache.wicket.Component.getString(Component.java:1955)
	at com.gitblit.wicket.pages.MyDashboardPage.readMarkdown(MyDashboardPage.java:219)
	at com.gitblit.wicket.pages.MyDashboardPage.setup(MyDashboardPage.java:86)
	at com.gitblit.wicket.pages.MyDashboardPage.<init>(MyDashboardPage.java:57)
	... 43 more
```

**Comment by gitblit** [comment]
Wicket stacktraces are quite noisey.  *Usually* the important bit is the last grouping, as is the case with these stacktraces.  After you filter out the nonsense you end up with...
```
Caused by: java.lang.NullPointerException
    at com.gitblit.wicket.pages.RootPage$UserMenu.onInitialize(RootPage.java:611)
```
and

```
Caused by: java.util.MissingResourceException: Unable to find property: 'gb.failedToRead' for component:  [class=com.gitblit.wicket.pages.MyDashboardPage]
    ...
    at com.gitblit.wicket.pages.MyDashboardPage.readMarkdown(MyDashboardPage.java:219)
```

Thanks for the details.  I'll see about getting these fixed for you.

**Comment by gitblit** [comment]
@Benjamin321 The first issue has already been corrected on `develop`.  The second issue is being masked by an exception thrown in the exception handler.  Nice, eh?  The second exception is related to your `web.repositoriesMessage` Markdown file.  Please check that this file exists, the path is correct, and it is **UTF-8** encoded.

**Comment by Benjamin321** [comment]
@gitblit Thanks, that was fast fixing! You were right, it looks like the Markdownfile was edited a while ago and was saved as CP1252 instead of UTF-8 encoded. So the second one was an error on my end.

**Comment by gitblit** [comment]
Fixed on `develop`.
